services:
  - type: web
    name: novoaspas
    env: node
    plan: free
    buildCommand: |
      npm install &&
      npx prisma generate &&
      npx prisma migrate deploy &&
      npx prisma db seed &&
      npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: novoaspas-db
          property: connectionString
      - key: NEXTAUTH_URL
        value: https://novoaspas.onrender.com
      - key: NEXTAUTH_SECRET
        value: ywxYI9zM8wSLswL54souB+WvwvjmyJ7I0pGVKKv8VuU=
      - key: NEXT_PUBLIC_API_URL
        value: https://novoaspas.onrender.com

  - type: postgres
    name: novoaspas-db
    plan: free
    ipAllowList: [] 