services:
  - type: web
    name: nextjs-app
    env: node
    buildCommand: |
      mkdir -p /opt/render/project/src/prisma &&
      chmod -R 777 /opt/render/project/src/prisma &&
      touch /opt/render/project/src/prisma/prod.db &&
      chmod 777 /opt/render/project/src/prisma/prod.db &&
      npm install &&
      npx prisma generate &&
      npx prisma db push &&
      npx prisma db seed &&
      npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: file:/opt/render/project/src/prisma/prod.db
      - key: NEXTAUTH_URL
        value: https://novoaspas.onrender.com
      - key: NEXTAUTH_SECRET
        value: use_uma_chave_secreta_muito_forte_aqui
    disk:
      name: sqlite
      mountPath: /opt/render/project/src/prisma
      sizeGB: 1
    autoDeploy: true 