services:
  - type: web
    name: nextjs-app
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true 